[package]
name = "abuse-helper"
version = "0.1.0"
authors = [
    "Elie Chamoun <elieechamoun@gmail.com>",
    "Habib Ayoub <habibbayoubb@gmail.com>",
]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.8"
actix-web-middleware-keycloak-auth = "0.4.2"
deadpool-postgres = "0.9.0"
dotenv = "0.15.0"
env_logger = "^0.8"
log = "^0.4"
serde = "1.0"
serde_json = "1.0"
tokio-postgres = "^0.7"
tokio-postgres-migration = "^0.1"
whois-rust = { version = "1.6.0", features = ["tokio"] }
